### ISSUE TITLE
Generation of blank document throws XSL-FO error

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iho#90]
Happens in metanorma-iho rspec:

     RuntimeError:
       [mn2pdf] Fatal: mn2pdf Preparing...
       Input: Fonts path ()
       Input: XML (test.presentation.xml)
       Input: XSL (/Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iho/lib/isodoc/iho/iho.standard.xsl)
       Output: PDF (test.pdf)
     
       [INFO] XSL-FO file preparation...
       Transforming to PDF...
       Default page-height set to: 11.00in
       Default page-width set to: 8.50in
       An fo:block-container  (See position 1:57174) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
       Content overflows the viewport of an fo:block-container in inline-progression direction by 18141 millipoints. (See position 1:5942)
       Rendered page #1.
       Rendered page #2.
       Rendered page #3.
       Rendered page #4.
       javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 25:3659)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
       	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:543)
       	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:414)
       	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:302)
       	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
       Caused by: org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 25:3659)
       	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
       	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
       	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
       	at com.sun.proxy.$Proxy10.missingChildElement(Unknown Source)
       	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
       	at org.apache.fop.fo.flow.BlockContainer.endOfNode(BlockContainer.java:144)
       	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
       	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:352)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
       	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
       	... 4 more
       ---------
       org.apache.fop.fo.ValidationException: "fo:block-container" is missing child elements. Required content model: marker* (%block;)+ (See position 25:3659)
       	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
       	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
       	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
       	at com.sun.proxy.$Proxy10.missingChildElement(Unknown Source)
       	at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:608)
       	at org.apache.fop.fo.flow.BlockContainer.endOfNode(BlockContainer.java:144)
       	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
       	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:352)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
       	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
       	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
       	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
       	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
       	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
       	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
       	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:543)
       	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:414)
       	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:302)
       	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
       XSL-FO file for debugging saved into: /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iho/test.pdf.fo.debug.xml

[test.pdf.fo.debug.zip](https://github.com/metanorma/metanorma-iho/files/10055956/test.pdf.fo.debug.zip)

**Comment by Intelligent2013** [comment]
Fixed.
